# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/lobster-tools',
                'doc_host': 'https://n-petit.github.io',
                'git_url': 'https://github.com/n-petit/lobster-tools',
                'lib_path': 'lobster_tools'},
  'syms': {'lobster_tools.core': {'lobster_tools.core.foo': ('core.html#foo', 'lobster_tools/core.py')}}}
