# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/07_arctic.ipynb.

# %% auto 0
__all__ = []

# %% ../notebooks/07_arctic.ipynb 4
import os

import click
from arcticdb import Arctic, LibraryOptions

# %% ../notebooks/07_arctic.ipynb 5
# | code-fold: true# | exports
# | code-fold: true
