# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/07_arctic.ipynb.

# %% auto 0
__all__ = ['CONTEXT_SETTINGS', 'test_arctic_db']

# %% ../notebooks/07_arctic.ipynb 4
import os
import sys

import click
from arcticdb import Arctic, LibraryOptions

# %% ../notebooks/07_arctic.ipynb 5
from .config import MainConfig, register_configs

# %% ../notebooks/07_arctic.ipynb 7
# | code-fold: true
CONTEXT_SETTINGS = dict(
    help_option_names=["-h", "--help"],
    token_normalize_func=lambda x: x.lower() if isinstance(x, str) else x,
    show_default=True,
)

@click.command(context_settings=CONTEXT_SETTINGS)
@click.option("-p", "--path", default="AMZN", help="ticker")
@click.option("-l", "--levels", default=5, help="number of levels")
def test_arctic_db(
):
    """Test connection to arctic database and list symbols."""

