# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/08_etf_pipeline_s3.ipynb.

# %% auto 0
__all__ = ['marginalize']

# %% ../notebooks/08_etf_pipeline_s3.ipynb 4
import os

import click
from arcticdb import Arctic, QueryBuilder
from hydra import initialize, initialize_config_module, initialize_config_dir, compose
from omegaconf import OmegaConf
from pathlib import Path
from .config import MainConfig, Overrides, register_configs, get_config, NASDAQExchange
from .preprocessing import *
from .querying import *
from .flow_decomposition import *
from .config import etf_to_equities
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.multioutput import MultiOutputRegressor
from itertools import product
import datetime as dt
from dataclasses import dataclass
from functools import partial
import json
from typing import Literal, cast
import numpy as np
from pprint import pprint
from collections import namedtuple

# %% ../notebooks/08_etf_pipeline_s3.ipynb 35
def marginalize(df: pd.DataFrame) -> pd.DataFrame:
    """Quidk implentation just for one feature. Just for _500us!"""
    # TODO think whether inplace is better
    df = df.copy()
    df["_500us_num_trades"] = df._500us_num_trades_os_af + df._500us_num_trades_os_bf + df._500us_num_trades_ss_af + df._500us_num_trades_ss_bf
    # same for others...
    return df
