# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/07_old_etf_pipeline_s3.ipynb.

# %% auto 0
__all__ = ['marginalize']

# %% ../notebooks/07_old_etf_pipeline_s3.ipynb 4
import datetime as dt
from collections import namedtuple
from dataclasses import dataclass
from functools import partial
from itertools import product

import numpy as np
import pandas as pd
from arcticdb import Arctic, QueryBuilder
from sklearn.linear_model import LinearRegression
from sklearn.multioutput import MultiOutputRegressor

from .config import NASDAQExchange, Overrides, etf_to_equities, get_config
from .flow_decomposition import *
from .preprocessing import *
from .querying import *

# %% ../notebooks/07_old_etf_pipeline_s3.ipynb 35
def marginalize(df: pd.DataFrame) -> pd.DataFrame:
    """Quidk implentation just for one feature. Just for _500us!"""
    # TODO think whether inplace is better
    df = df.copy()
    df["_500us_num_trades"] = df._500us_num_trades_os_af + df._500us_num_trades_os_bf + df._500us_num_trades_ss_af + df._500us_num_trades_ss_bf
    # same for others...
    return df
